CREATE TABLE ACCESO (
    ACCESO_ID NUMBER NOT NULL,
    NOMBRE_USUARIO VARCHAR2(100) NOT NULL,
    CONTRASENA_HASH VARCHAR2(255) NOT NULL,
    ROL_ID NUMBER NOT NULL,
    AFILIADO_ID NUMBER,
    EMPRESA_ID NUMBER,
    ESTADO VARCHAR2(20) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_ACCESO
        PRIMARY KEY (ACCESO_ID),

    CONSTRAINT UK_ACCESO_NOMBRE
        UNIQUE (NOMBRE_USUARIO),

    CONSTRAINT CK_ACCESO_ESTADO
        CHECK (ESTADO IN ('ACTIVO', 'INACTIVO')),

    CONSTRAINT FK_ACCESO_ROL
        FOREIGN KEY (ROL_ID)
        REFERENCES ROL (ROL_ID),

    CONSTRAINT FK_ACCESO_AFILIADO
        FOREIGN KEY (AFILIADO_ID)
        REFERENCES AFILIADO (AFILIADO_ID),

    CONSTRAINT FK_ACCESO_EMPRESA
        FOREIGN KEY (EMPRESA_ID)
        REFERENCES EMPRESA (EMPRESA_ID)
);