CREATE TABLE AFILIADO (
    AFILIADO_ID NUMBER PRIMARY KEY,
    TIPO_DOCUMENTO VARCHAR2(10) NOT NULL,
    NUMERO_DOCUMENTO VARCHAR2(30) NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,

    CONSTRAINT CK_AFILIADO_TIPO_DOC
        CHECK (TIPO_DOCUMENTO IN ('CC', 'CE', 'TI', 'PA')),

    CONSTRAINT UK_AFILIADO_DOCUMENTO
        UNIQUE (TIPO_DOCUMENTO, NUMERO_DOCUMENTO),

    CONSTRAINT CK_AFILIADO_ESTADO
        CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
);