CREATE TABLE APORTES (
    APORTE_ID NUMBER PRIMARY KEY,
    AFILIADO_ID NUMBER NOT NULL,
    EMPRESA_ID NUMBER NOT NULL,
    PERIODO DATE NOT NULL,
    SALARIO_BASE NUMBER(12,2) NOT NULL,
    VALOR_APORTE NUMBER(12,2) NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT CK_APORTE_SALARIO
        CHECK (SALARIO_BASE > 0),

    CONSTRAINT CK_APORTE_VALOR
        CHECK (VALOR_APORTE > 0),

    CONSTRAINT CK_APORTE_ESTADO
        CHECK (ESTADO IN ('PENDIENTE', 'PAGADO', 'ANULADO')),

    CONSTRAINT UK_APORTE_PERIODO
        UNIQUE (AFILIADO_ID, EMPRESA_ID, PERIODO)
);