CREATE TABLE EMPRESA (
    EMPRESA_ID NUMBER PRIMARY KEY,
    NIT VARCHAR2(30) NOT NULL,
    RAZON_SOCIAL VARCHAR2(200) NOT NULL,
    ESTADO VARCHAR2(20) NOT NULL,
    DEUDA NUMBER(14,2) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,
    FECHA_ACTUALIZACION DATE,

    CONSTRAINT UK_EMPRESA_NIT
        UNIQUE (NIT),

    CONSTRAINT CK_EMPRESA_ESTADO
        CHECK (ESTADO IN ('ACTIVA', 'INACTIVA')),

    CONSTRAINT CK_EMPRESA_DEUDA
        CHECK (DEUDA >= 0)
);