CREATE TABLE ERROR_SISTEMA (
    ERROR_ID NUMBER PRIMARY KEY,
    CODIGO_ERROR NUMBER NOT NULL,
    NOMBRE_ERROR VARCHAR2(100) NOT NULL,
    MENSAJE VARCHAR2(500) NOT NULL,
    MODULO VARCHAR2(100) NOT NULL,
    SEVERIDAD VARCHAR2(20) NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT UK_ERROR_CODIGO
        UNIQUE (CODIGO_ERROR),

    CONSTRAINT CK_ERROR_SEVERIDAD
        CHECK (SEVERIDAD IN (
            'INFO',
            'WARN',
            'ERROR',
            'FATAL'
        ))
);