CREATE TABLE HISTORIAL_LABORAL (
    HISTORIAL_ID NUMBER PRIMARY KEY,
    AFILIADO_ID NUMBER NOT NULL,
    EMPRESA_ID NUMBER NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE,
    SALARIO NUMBER(12,2),
    CARGO VARCHAR2(100),

    CONSTRAINT CK_HISTORIAL_FECHA
        CHECK (FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_INICIO),

    CONSTRAINT CK_HISTORIAL_SALARIO
        CHECK (SALARIO IS NULL OR SALARIO >= 0)
);