CREATE TABLE ROL (
    ROL_ID NUMBER NOT NULL,
    NOMBRE_USUARIO VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(200),
    ESTADO VARCHAR2(20) NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT PK_ROL
        PRIMARY KEY (ROL_ID),

    CONSTRAINT UK_ROL_NOMBRE
        UNIQUE (NOMBRE),

    CONSTRAINT CK_ROL_ESTADO
        CHECK (ESTADO IN ('ACTIVO', 'INACTIVO'))
);


