CREATE TABLE SOLICITUD_PENSION (
    SOLICITUD_ID NUMBER PRIMARY KEY,
    AFILIADO_ID NUMBER NOT NULL,
    FECHA_SOLICITUD DATE NOT NULL,
    TIPO_PENSION VARCHAR2(30) NOT NULL,
    REGIMEN VARCHAR2(10) NOT NULL,
    ESTADO VARCHAR2(30) NOT NULL,
    OBSERVACION VARCHAR2(500),
    FECHA_DECISION DATE,

    CONSTRAINT CK_SOLICITUD_TIPO
        CHECK (TIPO_PENSION IN (
            'VEJEZ',
            'INVALIDEZ',
            'SOBREVIVIENTES'
        )),

    CONSTRAINT CK_SOLICITUD_REGIMEN
        CHECK (REGIMEN IN ('RPM', 'RAIS')),

    CONSTRAINT CK_SOLICITUD_ESTADO
        CHECK (ESTADO IN (
            'RADICADA',
            'EN_ESTUDIO',
            'APROBADA',
            'RECHAZADA'
        ))
);






