ALTER TABLE APORTES
ADD CONSTRAINT FK_APORTE_AFILIADO
FOREIGN KEY (AFILIADO_ID)
REFERENCES AFILIADO(AFILIADO_ID);

ALTER TABLE APORTES
ADD CONSTRAINT FK_APORTE_EMPRESA
FOREIGN KEY (EMPRESA_ID)
REFERENCES EMPRESA(EMPRESA_ID);

ALTER TABLE HISTORIAL_LABORAL
ADD CONSTRAINT FK_HISTORIAL_AFILIADO
FOREIGN KEY (AFILIADO_ID)
REFERENCES AFILIADO(AFILIADO_ID);

ALTER TABLE HISTORIAL_LABORAL
ADD CONSTRAINT FK_HISTORIAL_EMPRESA
FOREIGN KEY (EMPRESA_ID)
REFERENCES EMPRESA(EMPRESA_ID);

ALTER TABLE SOLICITUD_PENSION
ADD CONSTRAINT FK_SOLICITUD_AFILIADO
FOREIGN KEY (AFILIADO_ID)
REFERENCES AFILIADO(AFILIADO_ID);

ALTER TABLE NOTIFICACION_AFILIADO
ADD CONSTRAINT FK_NOTIFICACION_AFILIADO
FOREIGN KEY (AFILIADO_ID)
REFERENCES AFILIADO(AFILIADO_ID);