CREATE OR REPLACE NONEDITIONABLE PACKAGE PKG_AFILIADOS AS

    TYPE RC IS REF CURSOR;

    PROCEDURE SP_ADD_AFILIADO(
        P_TIPO_DOCUMENTO   IN VARCHAR2,
        P_NUMERO_DOCUMENTO IN VARCHAR2,
        P_NOMBRE           IN VARCHAR2,
        P_APELLIDO         IN VARCHAR2,
        P_FECHA_NACIMIENTO IN DATE,
        P_AFILIADO_ID      OUT NUMBER
    );

    PROCEDURE SP_DISABLE_AFILIADO(
        P_AFILIADO_ID IN NUMBER
    );
    
    PROCEDURE SP_ENABLE_AFILIADO(
        P_AFILIADO_ID IN NUMBER
    );    

    PROCEDURE SP_GET_ALL_AFILIADO(
        P_CURSOR OUT RC
    );
    
    PROCEDURE SP_GET_AFILIADO(
        P_AFILIADO_ID IN NUMBER,
        P_CURSOR OUT RC
    );
    
    PROCEDURE SP_UPDATE_AFILIADO(
        P_AFILIADO_ID IN NUMBER,
        P_TIPO_DOCUMENTO IN VARCHAR2,
        P_NUMERO_DOCUMENTO IN VARCHAR2,
        P_NOMBRE IN VARCHAR2,
        P_APELLIDO IN VARCHAR2,
        P_FECHA_NACIMIENTO IN DATE
    );
    
    FUNCTION FN_EDAD_AFILIADO(
    P_AFILIADO_ID IN NUMBER
    ) RETURN NUMBER;

END PKG_AFILIADOS;