create or replace NONEDITIONABLE PACKAGE BODY PKG_AFILIADOS AS

    PROCEDURE SP_ADD_AFILIADO(
        P_TIPO_DOCUMENTO   IN VARCHAR2,
        P_NUMERO_DOCUMENTO IN VARCHAR2,
        P_NOMBRE           IN VARCHAR2,
        P_APELLIDO         IN VARCHAR2,
        P_FECHA_NACIMIENTO IN DATE,
        P_AFILIADO_ID      OUT NUMBER
    ) AS

        V_ID NUMBER;

    BEGIN

        SELECT NVL(MAX(AFILIADO_ID), 0) + 1
        INTO V_ID
        FROM AFILIADO;

        INSERT INTO AFILIADO (
            AFILIADO_ID,
            TIPO_DOCUMENTO,
            NUMERO_DOCUMENTO,
            NOMBRE,
            APELLIDO,
            FECHA_NACIMIENTO,
            ESTADO
        )
        VALUES (
            V_ID,
            P_TIPO_DOCUMENTO,
            P_NUMERO_DOCUMENTO,
            P_NOMBRE,
            P_APELLIDO,
            P_FECHA_NACIMIENTO,
            'ACTIVO'
        );

        P_AFILIADO_ID := V_ID;

    END SP_ADD_AFILIADO;

    PROCEDURE SP_DISABLE_AFILIADO(
        P_AFILIADO_ID IN NUMBER
    ) AS
    BEGIN

        UPDATE AFILIADO
        SET ESTADO = 'INACTIVO'
        WHERE AFILIADO_ID = P_AFILIADO_ID;

    END SP_DISABLE_AFILIADO;

    PROCEDURE SP_ENABLE_AFILIADO(
        P_AFILIADO_ID IN NUMBER
    ) AS
    BEGIN
        
        UPDATE AFILIADO
        SET ESTADO = 'ACTIVO'
        WHERE AFILIADO_ID = P_AFILIADO_ID;
        
    END SP_ENABLE_AFILIADO;

    PROCEDURE SP_GET_ALL_AFILIADO(
        P_CURSOR OUT RC
    ) AS
    BEGIN

        OPEN P_CURSOR FOR
            SELECT *
            FROM AFILIADO
            ORDER BY AFILIADO_ID;

    END SP_GET_ALL_AFILIADO;
    
    
    PROCEDURE SP_GET_AFILIADO(
        P_AFILIADO_ID IN NUMBER,
        P_CURSOR OUT RC
    ) AS
    BEGIN

    OPEN P_CURSOR FOR
        SELECT *
        FROM AFILIADO
        WHERE AFILIADO_ID = P_AFILIADO_ID
        ORDER BY AFILIADO_ID;

    END SP_GET_AFILIADO;
    
    PROCEDURE SP_UPDATE_AFILIADO(
        P_AFILIADO_ID      IN NUMBER,
        P_TIPO_DOCUMENTO   IN VARCHAR2,
        P_NUMERO_DOCUMENTO IN VARCHAR2,
        P_NOMBRE           IN VARCHAR2,
        P_APELLIDO         IN VARCHAR2,
        P_FECHA_NACIMIENTO IN DATE
    ) AS
    BEGIN
    
        UPDATE AFILIADO
        SET TIPO_DOCUMENTO   = P_TIPO_DOCUMENTO,
            NUMERO_DOCUMENTO = P_NUMERO_DOCUMENTO,
            NOMBRE           = P_NOMBRE,
            APELLIDO         = P_APELLIDO,
            FECHA_NACIMIENTO = P_FECHA_NACIMIENTO
        WHERE AFILIADO_ID = P_AFILIADO_ID;

    END SP_UPDATE_AFILIADO;
    
    FUNCTION FN_EDAD_AFILIADO(
    P_AFILIADO_ID IN NUMBER
    ) 
        RETURN NUMBER IS 
            V_EDAD NUMBER;
            V_FECHA_NACIMIENTO DATE;
    BEGIN
        SELECT FECHA_NACIMIENTO
        INTO V_FECHA_NACIMIENTO
        FROM AFILIADO
        WHERE AFILIADO_ID = P_AFILIADO_ID;
        
        V_EDAD := TRUNC(MONTHS_BETWEEN(SYSDATE, V_FECHA_NACIMIENTO) / 12);
        
        RETURN V_EDAD;
            
    END FN_EDAD_AFILIADO;

END PKG_AFILIADOS;
